--BEGIN MIGRATION UP--
CREATE TABLE users (
  id serial NOT NULL PRIMARY KEY,
  username varchar(24) UNIQUE
);
INSERT INTO users (username) VALUES ('tlhunter');
--END MIGRATION UP--
--BEGIN MIGRATION DOWN--
DROP TABLE users;
--END MIGRATION DOWN--